from enum import Enum


class Roles(Enum):
    MARKETPLACE_ADMIN = "MARKETPLACE_ADMIN"
    MARKETPLACE_USER = "MARKETPLACE_USER"
    STORE_USER = "STORE_USER"


class DeliverStatus(Enum):
    CREATED = "CREATED"
    CONFIRMED = "CONFIRMED"
    DISPACHED = "DISPACHED"
    DELIVERED = "DELIVERED"


class OrderStatus(Enum):
    READY_FOR_PICK_UP = "READY_FOR_PICK_UP"
    AT_ORIGIN = "AT_ORIGIN"
    EN_ROUTE_OF_DELIVERY = "EN_ROUTE_OF_DELIVERY"
    NOT_DELIVERED = "NOT_DELIVERED"
    DELIVERED = "DELIVERED"
    PENDING = "PENDING"
