name: Docker Image CI

on:
  pull_request:
    branches: [ "develop" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build and run the docker containers
      run: docker-compose up -d --build
    
    - name: Test the ecommerce service
      run: docker exec ecommerce-service python -m pytest -rP
      
    - name: Test the delivery service
      run: docker exec delivery-service python -m pytest -rP
      
    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
